name: Build Menbr APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - run: flutter create menbr_temp
      - run: cp pubspec.yaml menbr_temp/
      - run: cp -r lib menbr_temp/
      - run: cp google-services.json menbr_temp/android/app/
      - run: cd menbr_temp && flutter pub get
      - run: cd menbr_temp && flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: Menbr-APK
          path: menbr_temp/build/app/outputs/flutter-apk/app-release.apk
